const PricingItem = require('../models/PricingItem');

const commonMedicationNote =
  'Seeded starter formulary informed by common hospital and pharmacy patterns across Zambia, Ghana, India, the UK, and the US, using WHO essential-medicines style grouping.';
const commonServiceNote =
  'Seeded starter service catalog informed by common hospital registration, consultation, laboratory, and administrative workflows across Zambia, Ghana, India, the UK, and the US.';

const medication = (code, name, category, brand = '', notes = commonMedicationNote) => ({
  itemType: 'Medication',
  catalogSection: 'Medication',
  code,
  name,
  category,
  brand,
  department: 'Pharmacy',
  unitPrice: 0,
  stockQuantity: 0,
  notes,
  isActive: true,
});

const medicalCondition = (code, name, category, department = '', notes = commonServiceNote) => ({
  itemType: 'Service',
  catalogSection: 'Medical Condition',
  code,
  name,
  category,
  brand: '',
  department,
  unitPrice: 0,
  stockQuantity: 0,
  notes,
  isActive: true,
});

const diagnosis = (code, name, category, department = '', notes = commonServiceNote) => ({
  itemType: 'Service',
  catalogSection: 'Diagnosis',
  code,
  name,
  category,
  brand: '',
  department,
  unitPrice: 0,
  stockQuantity: 0,
  notes,
  isActive: true,
});

const labTest = (code, name, category, notes = commonServiceNote) => ({
  itemType: 'Service',
  catalogSection: 'Lab Test',
  code,
  name,
  category,
  brand: '',
  department: 'Laboratory',
  unitPrice: 0,
  stockQuantity: 0,
  notes,
  isActive: true,
});

const administrativeService = (code, name, category, department = '', notes = commonServiceNote) => ({
  itemType: 'Service',
  catalogSection: 'Administrative',
  code,
  name,
  category,
  brand: '',
  department,
  unitPrice: 0,
  stockQuantity: 0,
  notes,
  isActive: true,
});

const seedItems = [
  medication('MED-ANLG-001', 'Paracetamol 500mg Tablet', 'Analgesic'),
  medication('MED-ANLG-002', 'Ibuprofen 400mg Tablet', 'Anti-inflammatory'),
  medication('MED-ANLG-003', 'Diclofenac 50mg Tablet', 'Anti-inflammatory'),
  medication('MED-ANLG-004', 'Tramadol 50mg Capsule', 'Analgesic'),
  medication('MED-ANLG-005', 'Morphine 10mg Injection', 'Analgesic'),
  medication('MED-ANLG-006', 'Aspirin 75mg Tablet', 'Cardiovascular'),
  medication('MED-ABX-001', 'Amoxicillin 500mg Capsule', 'Antibiotic'),
  medication('MED-ABX-002', 'Amoxicillin-Clavulanate 625mg Tablet', 'Antibiotic'),
  medication('MED-ABX-003', 'Ceftriaxone 1g Injection', 'Antibiotic'),
  medication('MED-ABX-004', 'Cefuroxime 500mg Tablet', 'Antibiotic'),
  medication('MED-ABX-005', 'Azithromycin 500mg Tablet', 'Antibiotic'),
  medication('MED-ABX-006', 'Erythromycin 500mg Tablet', 'Antibiotic'),
  medication('MED-ABX-007', 'Ciprofloxacin 500mg Tablet', 'Antibiotic'),
  medication('MED-ABX-008', 'Metronidazole 400mg Tablet', 'Antibiotic'),
  medication('MED-ABX-009', 'Doxycycline 100mg Capsule', 'Antibiotic'),
  medication('MED-ABX-010', 'Flucloxacillin 500mg Capsule', 'Antibiotic'),
  medication('MED-ABX-011', 'Gentamicin 80mg Injection', 'Antibiotic'),
  medication('MED-ABX-012', 'Co-trimoxazole 960mg Tablet', 'Antibiotic'),
  medication('MED-ABX-013', 'Nitrofurantoin 100mg Capsule', 'Antibiotic'),
  medication('MED-AFM-001', 'Fluconazole 150mg Capsule', 'Antifungal'),
  medication('MED-AFM-002', 'Clotrimazole 1% Cream', 'Antifungal'),
  medication('MED-AFM-003', 'Nystatin Oral Suspension', 'Antifungal'),
  medication('MED-AVR-001', 'Acyclovir 400mg Tablet', 'Antiviral'),
  medication('MED-AML-001', 'Artemether-Lumefantrine Tablet', 'Antimalarial'),
  medication('MED-AML-002', 'Artesunate 60mg Injection', 'Antimalarial'),
  medication('MED-AML-003', 'Quinine 300mg Tablet', 'Antimalarial'),
  medication('MED-AML-004', 'Sulfadoxine-Pyrimethamine Tablet', 'Antimalarial'),
  medication('MED-ANT-001', 'Albendazole 400mg Tablet', 'Antiparasitic'),
  medication('MED-ANT-002', 'Mebendazole 100mg Tablet', 'Antiparasitic'),
  medication('MED-CVS-001', 'Amlodipine 5mg Tablet', 'Antihypertensive'),
  medication('MED-CVS-002', 'Lisinopril 10mg Tablet', 'Antihypertensive'),
  medication('MED-CVS-003', 'Losartan 50mg Tablet', 'Antihypertensive'),
  medication('MED-CVS-004', 'Hydrochlorothiazide 25mg Tablet', 'Antihypertensive'),
  medication('MED-CVS-005', 'Furosemide 40mg Tablet', 'Cardiovascular'),
  medication('MED-CVS-006', 'Atenolol 50mg Tablet', 'Cardiovascular'),
  medication('MED-CVS-007', 'Bisoprolol 5mg Tablet', 'Cardiovascular'),
  medication('MED-CVS-008', 'Atorvastatin 20mg Tablet', 'Cardiovascular'),
  medication('MED-END-001', 'Metformin 500mg Tablet', 'Antidiabetic'),
  medication('MED-END-002', 'Glibenclamide 5mg Tablet', 'Antidiabetic'),
  medication('MED-END-003', 'Insulin Soluble Injection', 'Antidiabetic'),
  medication('MED-END-004', 'Insulin Isophane (NPH) Injection', 'Antidiabetic'),
  medication('MED-GIT-001', 'Omeprazole 20mg Capsule', 'Gastrointestinal'),
  medication('MED-GIT-002', 'Pantoprazole 40mg Injection', 'Gastrointestinal'),
  medication('MED-GIT-003', 'Oral Rehydration Salts Sachet', 'Gastrointestinal'),
  medication('MED-GIT-004', 'Zinc Sulfate 20mg Tablet', 'Gastrointestinal'),
  medication('MED-GIT-005', 'Ondansetron 4mg Tablet', 'Gastrointestinal'),
  medication('MED-GIT-006', 'Metoclopramide 10mg Injection', 'Gastrointestinal'),
  medication('MED-RSP-001', 'Salbutamol Inhaler 100mcg', 'Respiratory'),
  medication('MED-RSP-002', 'Salbutamol Nebules', 'Respiratory'),
  medication('MED-RSP-003', 'Beclometasone Inhaler', 'Respiratory'),
  medication('MED-RSP-004', 'Aminophylline 250mg Injection', 'Respiratory'),
  medication('MED-EMR-001', 'Adrenaline 1mg Injection', 'Emergency/Anaphylaxis'),
  medication('MED-EMR-002', 'Hydrocortisone 100mg Injection', 'Emergency/Anaphylaxis'),
  medication('MED-EMR-003', 'Dexamethasone 8mg Injection', 'Emergency/Anaphylaxis'),
  medication('MED-EMR-004', 'Chlorpheniramine 10mg Injection', 'Emergency/Anaphylaxis'),
  medication('MED-ALR-001', 'Cetirizine 10mg Tablet', 'Antiallergic'),
  medication('MED-FLD-001', 'Normal Saline 0.9% Infusion', 'Electrolyte/Fluid'),
  medication('MED-FLD-002', 'Ringer Lactate Infusion', 'Electrolyte/Fluid'),
  medication('MED-FLD-003', 'Dextrose 5% Infusion', 'Electrolyte/Fluid'),
  medication('MED-FLD-004', 'Dextrose Saline Infusion', 'Electrolyte/Fluid'),
  medication('MED-FLD-005', 'Calcium Gluconate Injection', 'Electrolyte/Fluid'),
  medication('MED-SUP-001', 'Ferrous Sulfate Tablet', 'Vitamin/Supplement'),
  medication('MED-SUP-002', 'Folic Acid 5mg Tablet', 'Vitamin/Supplement'),
  medication('MED-SUP-003', 'Vitamin B Complex Tablet', 'Vitamin/Supplement'),
  medication('MED-SUP-004', 'Multivitamin Syrup', 'Vitamin/Supplement'),
  medication('MED-OBS-001', 'Oxytocin 10IU Injection', 'Obstetric'),
  medication('MED-OBS-002', 'Misoprostol 200mcg Tablet', 'Obstetric'),
  medication('MED-DER-001', 'Hydrocortisone 1% Cream', 'Dermatology'),
  medication('MED-DER-002', 'Silver Sulfadiazine Cream', 'Dermatology'),

  medicalCondition('CON-GEN-001', 'Malaria Case Management', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-002', 'Hypertension Review', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-003', 'Diabetes Review', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-004', 'Pneumonia Management', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-005', 'Typhoid Evaluation', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-006', 'Urinary Tract Infection Management', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-007', 'Gastroenteritis Management', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-008', 'Anaemia Review', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-009', 'Peptic Ulcer Disease Review', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-010', 'HIV Follow-Up Review', 'General Medicine', 'General OPD'),
  medicalCondition('CON-GEN-011', 'Tuberculosis Follow-Up Review', 'General Medicine', 'General OPD'),
  medicalCondition('CON-PED-001', 'Well Child Consultation', 'Pediatrics', 'Pediatrics'),
  medicalCondition('CON-PED-002', 'Paediatric Fever Review', 'Pediatrics', 'Pediatrics'),
  medicalCondition('CON-PED-003', 'Neonatal Review', 'Pediatrics', 'Pediatrics'),
  medicalCondition('CON-OBS-001', 'Antenatal Consultation', 'Obstetrics', 'Ward and Admissions'),
  medicalCondition('CON-OBS-002', 'Postnatal Consultation', 'Obstetrics', 'Ward and Admissions'),
  medicalCondition('CON-GYN-001', 'Menstrual Disorder Review', 'Gynecology', 'General OPD'),
  medicalCondition('CON-CAR-001', 'Heart Failure Review', 'Cardiology', 'Cardiology'),
  medicalCondition('CON-CAR-002', 'Chest Pain Evaluation', 'Cardiology', 'Cardiology'),
  medicalCondition('CON-SUR-001', 'Surgical Follow-Up', 'Surgery', 'Theatre'),
  medicalCondition('CON-SUR-002', 'Minor Procedure Review', 'Surgery', 'Theatre'),
  medicalCondition('CON-ORT-001', 'Back Pain Review', 'Orthopedics', 'General OPD'),
  medicalCondition('CON-ORT-002', 'Arthritis Review', 'Orthopedics', 'General OPD'),
  medicalCondition('CON-ENT-001', 'ENT Infection Review', 'ENT', 'General OPD'),
  medicalCondition('CON-DER-001', 'Dermatitis Review', 'Dermatology', 'General OPD'),
  medicalCondition('CON-DER-002', 'Skin Infection Review', 'Dermatology', 'General OPD'),
  medicalCondition('CON-OTH-001', 'Asthma Review', 'Other', 'General OPD'),
  medicalCondition('CON-OTH-002', 'Epilepsy Review', 'Other', 'General OPD'),
  medicalCondition('CON-OTH-003', 'Allergy Review', 'Other', 'General OPD'),
  medicalCondition('CON-OTH-004', 'Sickle Cell Disease Review', 'Other', 'General OPD'),
  medicalCondition('CON-OTH-005', 'Minor Trauma Care', 'Other', 'Emergency'),
  medicalCondition('CON-OTH-006', 'Wound Care Review', 'Other', 'Emergency'),
  medicalCondition('CON-OTH-007', 'STI Evaluation', 'Other', 'General OPD'),
  medicalCondition('CON-OTH-008', 'Mental Health Review', 'Other', 'General OPD'),

  diagnosis('DIA-INF-001', 'Malaria', 'Infectious Disease', 'General OPD'),
  diagnosis('DIA-INF-002', 'Severe Malaria', 'Infectious Disease', 'Emergency'),
  diagnosis('DIA-INF-003', 'Typhoid Fever', 'Infectious Disease', 'General OPD'),
  diagnosis('DIA-INF-004', 'Acute Gastroenteritis', 'Infectious Disease', 'General OPD'),
  diagnosis('DIA-INF-005', 'Urinary Tract Infection', 'Infectious Disease', 'General OPD'),
  diagnosis('DIA-INF-006', 'Pelvic Inflammatory Disease', 'Infectious Disease', 'Gynecology'),
  diagnosis('DIA-INF-007', 'Sexually Transmitted Infection', 'Infectious Disease', 'General OPD'),
  diagnosis('DIA-INF-008', 'Pulmonary Tuberculosis', 'Infectious Disease', 'General OPD'),
  diagnosis('DIA-INF-009', 'Bacterial Meningitis', 'Infectious Disease', 'Emergency'),
  diagnosis('DIA-INF-010', 'COVID-19 Infection', 'Infectious Disease', 'General OPD'),
  diagnosis('DIA-INF-011', 'Acute Tonsillitis', 'Infectious Disease', 'ENT'),
  diagnosis('DIA-INF-012', 'Cellulitis', 'Infectious Disease', 'General OPD'),

  diagnosis('DIA-RSP-001', 'Upper Respiratory Tract Infection', 'Respiratory', 'General OPD'),
  diagnosis('DIA-RSP-002', 'Pneumonia', 'Respiratory', 'General OPD'),
  diagnosis('DIA-RSP-003', 'Bronchial Asthma', 'Respiratory', 'General OPD'),
  diagnosis('DIA-RSP-004', 'Acute Exacerbation of Asthma', 'Respiratory', 'Emergency'),
  diagnosis('DIA-RSP-005', 'Chronic Obstructive Pulmonary Disease', 'Respiratory', 'General OPD'),
  diagnosis('DIA-RSP-006', 'Allergic Rhinitis', 'Respiratory', 'ENT'),

  diagnosis('DIA-GIT-001', 'Peptic Ulcer Disease', 'Gastrointestinal', 'General OPD'),
  diagnosis('DIA-GIT-002', 'Gastritis', 'Gastrointestinal', 'General OPD'),
  diagnosis('DIA-GIT-003', 'Gastroesophageal Reflux Disease', 'Gastrointestinal', 'General OPD'),
  diagnosis('DIA-GIT-004', 'Acute Appendicitis', 'Gastrointestinal', 'Surgery'),
  diagnosis('DIA-GIT-005', 'Constipation', 'Gastrointestinal', 'General OPD'),
  diagnosis('DIA-GIT-006', 'Hemorrhoids', 'Gastrointestinal', 'Surgery'),
  diagnosis('DIA-GIT-007', 'Acute Hepatitis', 'Gastrointestinal', 'General OPD'),

  diagnosis('DIA-CVS-001', 'Hypertension', 'Cardiovascular', 'General OPD'),
  diagnosis('DIA-CVS-002', 'Hypertensive Urgency', 'Cardiovascular', 'Emergency'),
  diagnosis('DIA-CVS-003', 'Heart Failure', 'Cardiovascular', 'Cardiology'),
  diagnosis('DIA-CVS-004', 'Ischemic Heart Disease', 'Cardiovascular', 'Cardiology'),
  diagnosis('DIA-CVS-005', 'Deep Vein Thrombosis', 'Cardiovascular', 'General OPD'),
  diagnosis('DIA-CVS-006', 'Stroke', 'Cardiovascular', 'Emergency'),

  diagnosis('DIA-END-001', 'Type 2 Diabetes Mellitus', 'Endocrine', 'General OPD'),
  diagnosis('DIA-END-002', 'Type 1 Diabetes Mellitus', 'Endocrine', 'Pediatrics'),
  diagnosis('DIA-END-003', 'Diabetic Ketoacidosis', 'Endocrine', 'Emergency'),
  diagnosis('DIA-END-004', 'Hypoglycaemia', 'Endocrine', 'Emergency'),
  diagnosis('DIA-END-005', 'Hyperthyroidism', 'Endocrine', 'General OPD'),
  diagnosis('DIA-END-006', 'Hypothyroidism', 'Endocrine', 'General OPD'),

  diagnosis('DIA-NEU-001', 'Epilepsy', 'Neurology', 'General OPD'),
  diagnosis('DIA-NEU-002', 'Migraine', 'Neurology', 'General OPD'),
  diagnosis('DIA-NEU-003', 'Tension Headache', 'Neurology', 'General OPD'),
  diagnosis('DIA-NEU-004', 'Peripheral Neuropathy', 'Neurology', 'General OPD'),

  diagnosis('DIA-PED-001', 'Neonatal Sepsis', 'Pediatrics', 'Pediatrics'),
  diagnosis('DIA-PED-002', 'Acute Otitis Media', 'Pediatrics', 'Pediatrics'),
  diagnosis('DIA-PED-003', 'Protein Energy Malnutrition', 'Pediatrics', 'Pediatrics'),
  diagnosis('DIA-PED-004', 'Acute Diarrheal Disease', 'Pediatrics', 'Pediatrics'),
  diagnosis('DIA-PED-005', 'Febrile Convulsion', 'Pediatrics', 'Pediatrics'),

  diagnosis('DIA-OBS-001', 'Normal Pregnancy', 'Obstetrics', 'Ward and Admissions'),
  diagnosis('DIA-OBS-002', 'Threatened Abortion', 'Obstetrics', 'Ward and Admissions'),
  diagnosis('DIA-OBS-003', 'Ectopic Pregnancy', 'Obstetrics', 'Emergency'),
  diagnosis('DIA-OBS-004', 'Pre-Eclampsia', 'Obstetrics', 'Ward and Admissions'),
  diagnosis('DIA-OBS-005', 'Eclampsia', 'Obstetrics', 'Emergency'),
  diagnosis('DIA-OBS-006', 'Postpartum Haemorrhage', 'Obstetrics', 'Emergency'),
  diagnosis('DIA-OBS-007', 'Prolonged Labour', 'Obstetrics', 'Ward and Admissions'),

  diagnosis('DIA-GYN-001', 'Dysmenorrhoea', 'Gynecology', 'Gynecology'),
  diagnosis('DIA-GYN-002', 'Uterine Fibroids', 'Gynecology', 'Gynecology'),
  diagnosis('DIA-GYN-003', 'Infertility', 'Gynecology', 'Gynecology'),
  diagnosis('DIA-GYN-004', 'Abnormal Uterine Bleeding', 'Gynecology', 'Gynecology'),

  diagnosis('DIA-SUR-001', 'Inguinal Hernia', 'Surgery', 'Surgery'),
  diagnosis('DIA-SUR-002', 'Soft Tissue Injury', 'Surgery', 'Emergency'),
  diagnosis('DIA-SUR-003', 'Burn Injury', 'Surgery', 'Emergency'),
  diagnosis('DIA-SUR-004', 'Post-Operative Review', 'Surgery', 'Surgery'),

  diagnosis('DIA-ORT-001', 'Osteoarthritis', 'Orthopedics', 'General OPD'),
  diagnosis('DIA-ORT-002', 'Low Back Pain', 'Orthopedics', 'General OPD'),
  diagnosis('DIA-ORT-003', 'Fracture', 'Orthopedics', 'Emergency'),
  diagnosis('DIA-ORT-004', 'Dislocation', 'Orthopedics', 'Emergency'),

  diagnosis('DIA-ENT-001', 'Otitis Externa', 'ENT', 'ENT'),
  diagnosis('DIA-ENT-002', 'Sinusitis', 'ENT', 'ENT'),
  diagnosis('DIA-ENT-003', 'Pharyngitis', 'ENT', 'ENT'),

  diagnosis('DIA-DER-001', 'Dermatitis', 'Dermatology', 'Dermatology'),
  diagnosis('DIA-DER-002', 'Tinea Infection', 'Dermatology', 'Dermatology'),
  diagnosis('DIA-DER-003', 'Scabies', 'Dermatology', 'Dermatology'),
  diagnosis('DIA-DER-004', 'Acne Vulgaris', 'Dermatology', 'Dermatology'),

  diagnosis('DIA-MHT-001', 'Anxiety Disorder', 'Mental Health', 'General OPD'),
  diagnosis('DIA-MHT-002', 'Depressive Disorder', 'Mental Health', 'General OPD'),
  diagnosis('DIA-MHT-003', 'Substance Use Disorder', 'Mental Health', 'General OPD'),

  diagnosis('DIA-EMR-001', 'Dehydration', 'Emergency', 'Emergency'),
  diagnosis('DIA-EMR-002', 'Anaemia', 'Emergency', 'Emergency'),
  diagnosis('DIA-EMR-003', 'Shock', 'Emergency', 'Emergency'),
  diagnosis('DIA-EMR-004', 'Poisoning', 'Emergency', 'Emergency'),

  diagnosis('DIA-OTH-001', 'Sickle Cell Disease', 'Other', 'General OPD'),
  diagnosis('DIA-OTH-002', 'Chronic Kidney Disease', 'Other', 'General OPD'),
  diagnosis('DIA-OTH-003', 'Conjunctivitis', 'Other', 'General OPD'),
  diagnosis('DIA-OTH-004', 'Dental Abscess', 'Other', 'General OPD'),
  diagnosis('DIA-OTH-005', 'Generalized Body Pains', 'Other', 'General OPD'),

  labTest('LAB-HEM-001', 'Full Blood Count (FBC/CBC)', 'Hematology'),
  labTest('LAB-HEM-002', 'Erythrocyte Sedimentation Rate (ESR)', 'Hematology'),
  labTest('LAB-HEM-003', 'Peripheral Blood Film', 'Hematology'),
  labTest('LAB-HEM-004', 'Prothrombin Time / INR', 'Hematology'),
  labTest('LAB-HEM-005', 'Activated Partial Thromboplastin Time (APTT)', 'Hematology'),
  labTest('LAB-HEM-006', 'Sickling Test', 'Hematology'),
  labTest('LAB-BBK-001', 'Blood Group and Rh Typing', 'Blood Bank'),
  labTest('LAB-BBK-002', 'Crossmatch', 'Blood Bank'),
  labTest('LAB-BCH-001', 'Random Blood Sugar', 'Chemistry'),
  labTest('LAB-BCH-002', 'Fasting Blood Sugar', 'Chemistry'),
  labTest('LAB-BCH-003', 'HbA1c', 'Chemistry'),
  labTest('LAB-BCH-004', 'Urea, Electrolytes and Creatinine', 'Chemistry'),
  labTest('LAB-BCH-005', 'Liver Function Test', 'Chemistry'),
  labTest('LAB-BCH-006', 'Lipid Profile', 'Chemistry'),
  labTest('LAB-BCH-007', 'C-Reactive Protein (CRP)', 'Chemistry'),
  labTest('LAB-BCH-008', 'Troponin', 'Chemistry'),
  labTest('LAB-BCH-009', 'Bone Profile', 'Chemistry'),
  labTest('LAB-BCH-010', 'Serum Calcium', 'Chemistry'),
  labTest('LAB-BCH-011', 'Serum Magnesium', 'Chemistry'),
  labTest('LAB-BCH-012', 'Amylase', 'Chemistry'),
  labTest('LAB-BCH-013', 'Thyroid Stimulating Hormone (TSH)', 'Chemistry'),
  labTest('LAB-URI-001', 'Urinalysis', 'Urinalysis'),
  labTest('LAB-URI-002', 'Urine Microscopy, Culture and Sensitivity', 'Urinalysis'),
  labTest('LAB-MIC-001', 'Blood Culture', 'Microbiology'),
  labTest('LAB-MIC-002', 'Sputum Microscopy, Culture and Sensitivity', 'Microbiology'),
  labTest('LAB-MIC-003', 'Wound Swab Microscopy, Culture and Sensitivity', 'Microbiology'),
  labTest('LAB-MIC-004', 'Stool Microscopy, Culture and Sensitivity', 'Microbiology'),
  labTest('LAB-MIC-005', 'H. pylori Stool Antigen', 'Microbiology'),
  labTest('LAB-SER-001', 'HIV 1 and 2 Rapid Test', 'Serology'),
  labTest('LAB-SER-002', 'HBsAg', 'Serology'),
  labTest('LAB-SER-003', 'Hepatitis C Antibody', 'Serology'),
  labTest('LAB-SER-004', 'VDRL / RPR', 'Serology'),
  labTest('LAB-SER-005', 'Pregnancy Test (Beta-hCG)', 'Serology'),
  labTest('LAB-PAR-001', 'Malaria Rapid Diagnostic Test', 'Parasitology'),
  labTest('LAB-PAR-002', 'Malaria Parasite Microscopy', 'Parasitology'),
  labTest('LAB-MOL-001', 'TB GeneXpert', 'Molecular'),
  labTest('LAB-MOL-002', 'COVID-19 PCR', 'Molecular'),

  administrativeService('ADM-REG-001', 'Patient Registration / File Opening', 'Consultation', 'Reception'),
  administrativeService('ADM-REG-002', 'Follow-Up Visit', 'Consultation', 'Reception'),
  administrativeService('ADM-CON-001', 'General Consultation Fee', 'Consultation', 'General OPD'),
  administrativeService('ADM-CON-002', 'Paediatric Consultation Fee', 'Consultation', 'Pediatrics'),
  administrativeService('ADM-CON-003', 'Specialist Consultation Fee', 'Consultation', 'Cardiology'),
  administrativeService('ADM-CON-004', 'Emergency Consultation Fee', 'Consultation', 'Emergency'),
  administrativeService('ADM-ADM-001', 'Admission Fee', 'Admission', 'Ward and Admissions'),
  administrativeService('ADM-ADM-002', 'Ward Bed Charge Per Day', 'Bed Charge', 'Ward and Admissions'),
  administrativeService('ADM-ADM-003', 'ICU Bed Charge Per Day', 'Bed Charge', 'Ward and Admissions'),
  administrativeService('ADM-PRC-001', 'Theatre Charge Per Hour', 'Procedure', 'Theatre'),
  administrativeService('ADM-PRC-002', 'Minor Procedure Room Charge', 'Procedure', 'Theatre'),
  administrativeService('ADM-NUR-001', 'Injection Administration Fee', 'Nursing', 'General OPD'),
  administrativeService('ADM-NUR-002', 'IV Cannulation Fee', 'Nursing', 'General OPD'),
  administrativeService('ADM-NUR-003', 'Wound Dressing Fee', 'Nursing', 'Emergency'),
  administrativeService('ADM-NUR-004', 'Nebulization Fee', 'Nursing', 'General OPD'),
  administrativeService('ADM-NUR-005', 'Observation / Day Care Fee', 'Nursing', 'Emergency'),
  administrativeService('ADM-OTH-001', 'Ambulance Transfer Fee', 'Other', 'Emergency'),
  administrativeService('ADM-OTH-002', 'Medical Report Fee', 'Other', 'Reception'),
  administrativeService('ADM-OTH-003', 'Insurance Processing Fee', 'Other', 'Cashier and Insurance'),
  administrativeService('ADM-OTH-004', 'Discharge Summary / Documentation Fee', 'Other', 'Ward and Admissions'),
  administrativeService('ADM-OTH-005', 'Antenatal Registration Fee', 'Other', 'Ward and Admissions'),
];

async function seedPricingCatalog() {
  await Promise.all(
    seedItems.map(async (item) => {
      const existingItem = await PricingItem.findOne({ code: item.code });

      if (existingItem) {
        existingItem.itemType = item.itemType;
        existingItem.catalogSection = item.catalogSection;
        existingItem.category = item.category;
        existingItem.name = item.name;
        existingItem.brand = item.brand;
        existingItem.department = item.department;
        existingItem.notes = item.notes;
        existingItem.isActive = item.isActive !== false;
        await existingItem.save();
        return existingItem;
      }

      return PricingItem.create(item);
    })
  );
}

module.exports = { seedPricingCatalog };
