import { useEffect, useMemo, useState } from 'react';
import { hospitalApi } from '../api/hospitalApi';
import { useToast } from '../app/ToastContext';
import Modal from '../components/common/Modal';
import PageHeader from '../components/common/PageHeader';
import SectionCard from '../components/common/SectionCard';
import StatCard from '../components/common/StatCard';
import TableToolbar from '../components/common/TableToolbar';
import Tabs from '../components/common/Tabs';
import DataTable from '../components/tables/DataTable';
import { navigationModules } from '../data/hospitalData';

const hospitalColumns = [
  { key: 'hospitalId', header: 'Hospital ID' },
  { key: 'hospitalName', header: 'Hospital Name' },
  { key: 'adminUsername', header: 'Admin Username' },
  { key: 'dbName', header: 'Database' },
  {
    key: 'enabledModules',
    header: 'Modules',
    render: (value) => `${(value || []).length} enabled`,
  },
  {
    key: 'seedStatus',
    header: 'Seed Common Data',
    badge: true,
    render: (_, row) => (row.sharedCatalogsSeededAt ? 'Seeded' : row.seedSharedCatalogs ? 'Queued' : 'Not seeded'),
  },
  { key: 'isActive', header: 'Status', badge: true, render: (value) => (value ? 'Active' : 'Inactive') },
];

const emptyHospitalForm = {
  id: '',
  hospitalName: '',
  hospitalId: '',
  dbName: '',
  adminFullName: '',
  adminUsername: '',
  pin: '',
  contactEmail: '',
  contactPhone: '',
  subscriptionCurrency: 'GHS',
  seedSharedCatalogs: true,
  sharedCatalogsSeededAt: null,
  subscriptionMonthlyAmount: 0,
  subscriptionExpiresAt: '',
  subscriptionActivationCode: '',
  subscriptionActivationCodeIssuedAt: null,
  subscriptionActivationCodeUsedAt: null,
  subscriptionLastPaymentAt: null,
  subscriptionLastActivatedAt: null,
  generateActivationCode: false,
  enabledModules: [],
  isActive: true,
};

const currencyOptions = [
  { code: 'GHS', label: 'GHS - Ghana Cedi' },
  { code: 'ZMW', label: 'ZMW - Zambian Kwacha' },
  { code: 'NGN', label: 'NGN - Nigerian Naira' },
  { code: 'KES', label: 'KES - Kenyan Shilling' },
  { code: 'USD', label: 'USD - US Dollar' },
  { code: 'GBP', label: 'GBP - British Pound' },
];

function buildModuleGroups() {
  return navigationModules
    .filter((module) => module.id !== 'hospital_management')
    .map((module) =>
      module.children?.length
        ? {
            id: module.id,
            label: module.label,
            options: module.children.map((child) => ({
              id: child.id,
              label: child.label,
              description: child.description,
            })),
          }
        : {
            id: module.id,
            label: module.label,
            options: [
              {
                id: module.id,
                label: module.label,
                description: module.description,
              },
            ],
          }
    );
}

const moduleGroups = buildModuleGroups();
const allTenantModuleIds = moduleGroups.flatMap((group) => group.options.map((option) => option.id));

function buildDatabaseNamePreview(hospitalId) {
  const normalizedId = String(hospitalId || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');

  return normalizedId ? `tenant_${normalizedId}` : 'Auto-generated by system';
}

function HospitalManagementPage({ data, auth, onRefreshData, pageMeta }) {
  const [records, setRecords] = useState(data.records || []);
  const [searchValue, setSearchValue] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [editingHospitalId, setEditingHospitalId] = useState(null);
  const [activeTab, setActiveTab] = useState('details');
  const [form, setForm] = useState({
    ...emptyHospitalForm,
    enabledModules: allTenantModuleIds,
  });
  const { showToast } = useToast();

  useEffect(() => {
    setRecords(data.records || []);
  }, [data.records]);

  const isMasterSuperAdmin = Boolean(auth.currentUser?.isMasterTenant && auth.currentUser?.isSuperAdmin);

  const summaryCards = useMemo(
    () => [
      { label: 'Hospitals', value: records.length },
      { label: 'Active', value: records.filter((item) => item.isActive !== false).length },
      { label: 'Seeded', value: records.filter((item) => item.seedSharedCatalogs).length },
    ],
    [records]
  );

  const filteredRecords = useMemo(
    () =>
      records.filter((item) =>
        [
          item.hospitalId,
          item.hospitalName,
          item.adminUsername,
          item.dbName,
          item.contactEmail,
          item.contactPhone,
        ]
          .join(' ')
          .toLowerCase()
          .includes(searchValue.toLowerCase())
      ),
    [records, searchValue]
  );

  if (!isMasterSuperAdmin) {
    return (
      <SectionCard eyebrow="Access control" title="Hospital management is restricted">
        <p className="panel-copy">Only the master super admin can create and manage hospital tenants.</p>
      </SectionCard>
    );
  }

  const openCreateModal = () => {
    setEditingHospitalId(null);
    setActiveTab('details');
    setForm({
      ...emptyHospitalForm,
      pin: '',
      seedSharedCatalogs: true,
      subscriptionCurrency: 'GHS',
      enabledModules: allTenantModuleIds,
      isActive: true,
    });
    setIsModalOpen(true);
  };

  const openEditModal = (hospital) => {
    setEditingHospitalId(hospital.id);
    setActiveTab('details');
    setForm({
      id: hospital.id,
      hospitalName: hospital.hospitalName || '',
      hospitalId: hospital.hospitalId || '',
      dbName: hospital.dbName || '',
      adminFullName: hospital.adminFullName || '',
      adminUsername: hospital.adminUsername || '',
      pin: '',
      contactEmail: hospital.contactEmail || '',
      contactPhone: hospital.contactPhone || '',
      subscriptionCurrency: hospital.subscriptionCurrency || 'GHS',
      seedSharedCatalogs: Boolean(hospital.seedSharedCatalogs),
      enabledModules: hospital.enabledModules?.length ? hospital.enabledModules : allTenantModuleIds,
      isActive: hospital.isActive !== false,
      sharedCatalogsSeededAt: hospital.sharedCatalogsSeededAt || null,
      subscriptionMonthlyAmount: Number(hospital.subscriptionMonthlyAmount || 0),
      subscriptionExpiresAt: hospital.subscriptionExpiresAt
        ? new Date(hospital.subscriptionExpiresAt).toISOString().slice(0, 10)
        : '',
      subscriptionActivationCode: hospital.subscriptionActivationCode || '',
      subscriptionActivationCodeIssuedAt: hospital.subscriptionActivationCodeIssuedAt || null,
      subscriptionActivationCodeUsedAt: hospital.subscriptionActivationCodeUsedAt || null,
      subscriptionLastPaymentAt: hospital.subscriptionLastPaymentAt || null,
      subscriptionLastActivatedAt: hospital.subscriptionLastActivatedAt || null,
      generateActivationCode: false,
    });
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setIsSaving(false);
    setEditingHospitalId(null);
    setActiveTab('details');
  };

  const handleChange = (event) => {
    const { name, value, type, checked } = event.target;

    setForm((current) => {
      const nextValue =
        type === 'checkbox' ? checked : name === 'isActive' ? value === 'true' : value;
      const nextForm = {
        ...current,
        [name]: nextValue,
      };
      return nextForm;
    });
  };

  const handleModuleToggle = (moduleId) => {
    setForm((current) => ({
      ...current,
      enabledModules: current.enabledModules.includes(moduleId)
        ? current.enabledModules.filter((item) => item !== moduleId)
        : [...current.enabledModules, moduleId],
    }));
  };

  const handleGenerateActivationCode = () => {
    setForm((current) => ({
      ...current,
      generateActivationCode: true,
    }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setIsSaving(true);

    try {
      const savedHospital = editingHospitalId
        ? await hospitalApi.updateHospital(editingHospitalId, form)
        : await hospitalApi.createHospital(form);
      const updatedRecords = editingHospitalId
        ? records.map((item) => (item.id === savedHospital.id ? savedHospital : item))
        : [savedHospital, ...records];
      setRecords(updatedRecords);
      closeModal();
      showToast(
        editingHospitalId ? 'Hospital tenant updated successfully.' : 'Hospital tenant created successfully.',
        'success'
      );
      if (onRefreshData) {
        await onRefreshData();
      }
    } catch (error) {
      setIsSaving(false);
      showToast(error.message || 'Unable to create hospital tenant.', 'error');
    }
  };

  return (
    <div className="page-stack">
      <PageHeader
        title={pageMeta?.label || 'Hospital Management'}
        description={pageMeta?.description || ''}
        actions={
          <button type="button" className="primary-button" onClick={openCreateModal}>
            Create Hospital
          </button>
        }
      />

      <div className="stats-grid stats-grid-compact">
        {summaryCards.map((item) => (
          <StatCard key={item.label} {...item} />
        ))}
      </div>

      <section className="panel">
        <TableToolbar
          searchValue={searchValue}
          onSearchChange={setSearchValue}
          searchPlaceholder="Search hospital ID, name, admin username, or database"
          filters={[]}
        />

        <DataTable
          columns={hospitalColumns}
          rows={filteredRecords}
          caption="Registered hospital tenants"
          onRowClick={openEditModal}
          emptyMessage="No hospital tenants have been created yet."
        />
      </section>

      <Modal
        isOpen={isModalOpen}
        title={editingHospitalId ? 'Edit Hospital Tenant' : 'Create Hospital Tenant'}
        subtitle={
          editingHospitalId
            ? 'Update tenant modules, status, contact details, and seed the shared starter data once if needed.'
            : "Create a hospital account, assign modules, and generate the tenant's default admin login."
        }
        onClose={closeModal}
      >
        <Tabs
          tabs={[
            { id: 'details', label: 'Details' },
            { id: 'subscription', label: 'Subscription' },
          ]}
          activeTab={activeTab}
          onChange={setActiveTab}
        />
        <form className="entity-form" onSubmit={handleSubmit}>
          {activeTab === 'details' ? (
            <>
              <div className="form-grid">
                <label className="form-field">
                  <span>Hospital Name</span>
                  <input name="hospitalName" value={form.hospitalName} onChange={handleChange} required />
                </label>
                <label className="form-field">
                  <span>Hospital ID</span>
                  <input name="hospitalId" value={form.hospitalId} onChange={handleChange} required disabled={Boolean(editingHospitalId)} />
                </label>
                <label className="form-field">
                  <span>Generated Database Name</span>
                  <input
                    value={editingHospitalId ? form.dbName : buildDatabaseNamePreview(form.hospitalId)}
                    disabled
                  />
                </label>
                <label className="form-field">
                  <span>Default Admin Full Name</span>
                  <input name="adminFullName" value={form.adminFullName} onChange={handleChange} required />
                </label>
                <label className="form-field">
                  <span>Default Admin Username</span>
                  <input
                    name="adminUsername"
                    value={form.adminUsername}
                    onChange={handleChange}
                    required
                    disabled={Boolean(editingHospitalId)}
                  />
                </label>
                <label className="form-field">
                  <span>Default Admin PIN</span>
                  <input
                    name="pin"
                    type="password"
                    value={form.pin}
                    onChange={handleChange}
                    inputMode="numeric"
                    pattern="[0-9]{4,6}"
                    required={!editingHospitalId}
                  />
                </label>
                <label className="form-field">
                  <span>Tenant Status</span>
                  <select name="isActive" value={String(form.isActive)} onChange={handleChange}>
                    <option value="true">Active</option>
                    <option value="false">Inactive</option>
                  </select>
                </label>
                <label className="form-field">
                  <span>Contact Email</span>
                  <input name="contactEmail" value={form.contactEmail} onChange={handleChange} />
                </label>
                <label className="form-field">
                  <span>Contact Phone</span>
                  <input name="contactPhone" value={form.contactPhone} onChange={handleChange} />
                </label>
                <label className="form-field">
                  <span>Tenant Currency</span>
                  <select name="subscriptionCurrency" value={form.subscriptionCurrency} onChange={handleChange}>
                    {currencyOptions.map((currency) => (
                      <option key={currency.code} value={currency.code}>
                        {currency.label}
                      </option>
                    ))}
                  </select>
                </label>
              </div>

              <div className="form-section">
                <div className="form-section-header">
                  <div>
                    <h4 className="form-section-title">Enabled Modules</h4>
                  </div>
                </div>
                <div className="line-item-stack">
                  {moduleGroups.map((group) => (
                    <div className="line-item-card" key={group.id}>
                      <strong>{group.label}</strong>
                      <div className="permission-grid">
                        {group.options.map((option) => (
                          <label key={option.id} className="checkbox-card">
                            <input
                              type="checkbox"
                              checked={form.enabledModules.includes(option.id)}
                              onChange={() => handleModuleToggle(option.id)}
                            />
                            <span>{option.label}</span>
                          </label>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <label className="checkbox-card">
                <input
                  type="checkbox"
                  name="seedSharedCatalogs"
                  checked={form.seedSharedCatalogs}
                  onChange={handleChange}
                  disabled={Boolean(form.sharedCatalogsSeededAt)}
                />
                <span>Seed departments, categories, medications, diagnoses, medical conditions, and lab tests</span>
              </label>
              {form.sharedCatalogsSeededAt ? (
                <p className="panel-copy">Shared starter data has already been seeded for this tenant and will not run again.</p>
              ) : null}
              {editingHospitalId ? (
                <p className="panel-copy">Clicking a tenant row opens this editor. Hospital ID, database name, and admin username stay locked to avoid cross-tenant conflicts.</p>
              ) : null}
            </>
          ) : (
            <>
              <div className="form-grid">
                <label className="form-field">
                  <span>Monthly Subscription Amount</span>
                  <input
                    name="subscriptionMonthlyAmount"
                    type="number"
                    min="0"
                    step="0.01"
                    value={form.subscriptionMonthlyAmount}
                    onChange={handleChange}
                  />
                </label>
                <label className="form-field">
                  <span>Subscription Currency</span>
                  <select name="subscriptionCurrency" value={form.subscriptionCurrency} onChange={handleChange}>
                    {currencyOptions.map((currency) => (
                      <option key={currency.code} value={currency.code}>
                        {currency.label}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="form-field">
                  <span>Subscription Expiry Date</span>
                  <input
                    name="subscriptionExpiresAt"
                    type="date"
                    value={form.subscriptionExpiresAt}
                    onChange={handleChange}
                  />
                </label>
                <label className="form-field">
                  <span>12-Character Activation Code</span>
                  <input
                    name="subscriptionActivationCode"
                    value={form.subscriptionActivationCode}
                    onChange={(event) =>
                      handleChange({
                        target: {
                          name: 'subscriptionActivationCode',
                          value: event.target.value.toUpperCase(),
                          type: 'text',
                        },
                      })
                    }
                    maxLength={12}
                    pattern="[A-Z0-9]{12}"
                  />
                </label>
              </div>

              <div className="page-header-actions">
                <button type="button" className="secondary-button" onClick={handleGenerateActivationCode}>
                  Generate New Activation Code
                </button>
              </div>
              {form.generateActivationCode ? (
                <p className="panel-copy">A new 12-character activation code will be generated when you save this tenant.</p>
              ) : null}
              {form.subscriptionActivationCodeIssuedAt ? (
                <p className="panel-copy">Code issued: {new Date(form.subscriptionActivationCodeIssuedAt).toLocaleString()}</p>
              ) : null}
              {form.subscriptionActivationCodeUsedAt ? (
                <p className="panel-copy">Last activation used: {new Date(form.subscriptionActivationCodeUsedAt).toLocaleString()}</p>
              ) : null}
              {form.subscriptionLastPaymentAt ? (
                <p className="panel-copy">Last Paystack payment: {new Date(form.subscriptionLastPaymentAt).toLocaleString()}</p>
              ) : null}
              {form.subscriptionLastActivatedAt ? (
                <p className="panel-copy">Last manual activation: {new Date(form.subscriptionLastActivatedAt).toLocaleString()}</p>
              ) : null}
            </>
          )}

          <div className="modal-actions">
            <button type="button" className="secondary-button" onClick={closeModal}>
              Cancel
            </button>
            <button type="submit" className="primary-button" disabled={isSaving}>
              {isSaving ? (editingHospitalId ? 'Saving...' : 'Creating...') : editingHospitalId ? 'Save Hospital' : 'Create Hospital'}
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
}

export default HospitalManagementPage;
